"""add model account related

Revision ID: 4fc340f6f399
Revises: c1ade52f4d8c
Create Date: 2025-02-12 10:05:21.604722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fc340f6f399'
down_revision: Union[str, None] = 'c1ade52f4d8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_auth_device',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.String(length=50), nullable=True, comment='用户唯一标识'),
    sa.Column('device_id', sa.String(length=50), nullable=True, comment='设备id，唯一标识指纹'),
    sa.Column('package_name', sa.String(length=32), nullable=True, comment='当前应用包名，应用唯一标识'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='网络IP'),
    sa.Column('user_agent', sa.String(length=255), nullable=True, comment='设备用户代理'),
    sa.Column('isp', sa.String(length=50), nullable=True, comment='网络运营商，云服务ip、机房ip、公司ip、住宅ip等，根据网络IP自动获取'),
    sa.Column('device_name', sa.String(length=50), nullable=True, comment='设备型号名'),
    sa.Column('device_type', sa.String(length=8), nullable=True, comment='设备类型，phone|tablet|pc|other'),
    sa.Column('hardware_name', sa.String(length=32), nullable=True, comment='设备硬件名'),
    sa.Column('push_token', sa.String(length=50), nullable=True, comment='消息推送token，如：firebase cloud messaging的推送token'),
    sa.Column('app_name', sa.String(length=32), nullable=True, comment='当前应用名（商店名称）'),
    sa.Column('app_version', sa.String(length=4), nullable=True, comment='当前应用版本号'),
    sa.Column('os_name', sa.String(length=8), nullable=True, comment='系统名，android|ios|windows|mac|linux|other'),
    sa.Column('os_version', sa.String(length=8), nullable=True, comment='系统版本'),
    sa.Column('country', sa.String(length=50), nullable=True, comment='系统国家'),
    sa.Column('language', sa.String(length=8), nullable=True, comment='系统语言'),
    sa.Column('timezone', sa.String(length=50), nullable=True, comment='系统时区'),
    sa.Column('screen_width', sa.Integer(), nullable=True, comment='屏幕宽度'),
    sa.Column('screen_height', sa.Integer(), nullable=True, comment='屏幕高度'),
    sa.Column('screen_density', sa.Float(), nullable=True, comment='屏幕像素分辨率'),
    sa.Column('external_storage', sa.Float(), nullable=True, comment='手机外置存储空间GB'),
    sa.Column('external_storage_overage', sa.Float(), nullable=True, comment='手机外置存储空间剩余GB'),
    sa.Column('network_carrier', sa.String(length=16), nullable=True, comment='特指设备的电信运营商，如Verizon、AT&T、Sprint、T-Mobile'),
    sa.Column('ad_id', sa.String(length=50), nullable=True, comment='设备广告标识符'),
    sa.Column('ad_id_type', sa.String(length=16), nullable=True, comment='广告标识类型，gaid|idfa|oaid|tifa|vida|rida|fire_adid|other'),
    sa.Column('referrer', sa.String(length=255), nullable=True, comment='谷歌深度链接'),
    sa.Column('attribution_source', sa.String(length=255), nullable=True, comment='归因来源（adjust归因结果/referrer解析utm_source）'),
    sa.Column('referrer_account_id', sa.String(length=255), nullable=True, comment='投放的广告账户id'),
    sa.Column('referrer_adgroup_id', sa.String(length=255), nullable=True, comment='投放的广告组id'),
    sa.Column('referrer_adgroup_name', sa.String(length=255), nullable=True, comment='投放的广告组名'),
    sa.Column('referrer_campaign_id', sa.String(length=255), nullable=True, comment='投放的广告系列名'),
    sa.Column('referrer_campaign_group_id', sa.String(length=255), nullable=True, comment='投放的广告系列归属组id名'),
    sa.Column('referrer_campaign_name', sa.String(length=255), nullable=True, comment='投放的广告系列名'),
    sa.Column('referrer_ad_id', sa.String(length=255), nullable=True, comment='投放的广告ID'),
    sa.Column('referrer_ad_name', sa.String(length=255), nullable=True, comment='投放的广告名（预留）'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_u_d_p', 'app_auth_device', ['user_uuid', 'device_id', 'package_name'], unique=True)
    op.create_index(op.f('ix_app_auth_device_push_token'), 'app_auth_device', ['push_token'], unique=False)
    op.create_index(op.f('ix_app_auth_device_user_uuid'), 'app_auth_device', ['user_uuid'], unique=False)
    op.create_table('app_auth_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.String(length=50), nullable=True, comment='用户唯一标识'),
    sa.Column('role_code', sa.String(length=16), nullable=True, comment='角色标识'),
    sa.Column('device_id', sa.String(length=50), nullable=True, comment='设备id，唯一标识指纹'),
    sa.Column('device_name', sa.String(length=50), nullable=True, comment='设备型号名'),
    sa.Column('os_name', sa.String(length=16), nullable=True, comment='系统名，android|ios|windows|mac|linux|other'),
    sa.Column('os_version', sa.String(length=8), nullable=True, comment='系统版本'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='网络IP'),
    sa.Column('user_agent', sa.String(length=255), nullable=True, comment='设备用户代理'),
    sa.Column('isp', sa.String(length=50), nullable=True, comment='网络运营商，机房ip、住宅ip等，根据网络IP库自动获取'),
    sa.Column('continent', sa.String(length=255), nullable=True, comment='所在大洲，根据网络IP库自动获取'),
    sa.Column('country', sa.String(length=50), nullable=True, comment='所在国家，根据网络IP库自动获取'),
    sa.Column('province', sa.String(length=255), nullable=True, comment='所在省份，根据网络IP库自动获取'),
    sa.Column('city', sa.String(length=255), nullable=True, comment='所在城市，根据网络IP库自动获取'),
    sa.Column('district', sa.String(length=255), nullable=True, comment='所在区县，根据网络IP库自动获取'),
    sa.Column('area_code', sa.String(length=255), nullable=True, comment='邮编区号，根据网络IP库自动获取'),
    sa.Column('country_code', sa.String(length=255), nullable=True, comment='国家代码，根据网络IP库自动获取'),
    sa.Column('longitude', sa.Float(), nullable=True, comment='经度'),
    sa.Column('latitude', sa.Float(), nullable=True, comment='纬度'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_auth_logs_user_uuid'), 'app_auth_logs', ['user_uuid'], unique=False)
    op.create_table('app_auth_sns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增ID'),
    sa.Column('user_uuid', sa.String(length=50), nullable=False, comment='用户唯一标识'),
    sa.Column('provider', sa.String(length=16), nullable=True, comment='社交平台（google|facebook|twitter|line|instagram|tiktok|github|linkedin|apple|microsoft）'),
    sa.Column('openid', sa.String(length=32), nullable=True, comment='社交平台用户唯一标识'),
    sa.Column('email', sa.String(length=50), nullable=True, comment='用户邮箱'),
    sa.Column('phone', sa.String(length=16), nullable=True, comment='用户手机号'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='用户昵称'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='用户头像URL'),
    sa.Column('gender', sa.Integer(), nullable=True, comment='用户性别（male|female|unknown）'),
    sa.Column('locale', sa.String(length=8), nullable=True, comment='用户语言'),
    sa.Column('region', sa.String(length=50), nullable=True, comment='用户地区'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_provider', 'app_auth_sns', ['user_uuid', 'provider'], unique=True)
    op.create_index(op.f('ix_app_auth_sns_email'), 'app_auth_sns', ['email'], unique=False)
    op.create_index(op.f('ix_app_auth_sns_openid'), 'app_auth_sns', ['openid'], unique=True)
    op.create_index(op.f('ix_app_auth_sns_provider'), 'app_auth_sns', ['provider'], unique=False)
    op.create_index(op.f('ix_app_auth_sns_user_uuid'), 'app_auth_sns', ['user_uuid'], unique=False)
    op.create_table('app_perms',
    sa.Column('id', sa.Integer(), nullable=False, comment='自增ID'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父级ID，上级权限ID'),
    sa.Column('current_id', sa.Integer(), nullable=True, comment='当前权限ID'),
    sa.Column('perms_title', sa.String(length=128), nullable=True, comment='权限名'),
    sa.Column('perms_type', sa.Integer(), nullable=True, comment='权限类型，目录|菜单页|普通页｜按钮'),
    sa.Column('perms_icon', sa.String(length=256), nullable=True, comment='权限图标名'),
    sa.Column('perms_comp', sa.String(length=64), nullable=True, comment='站内前端组件名'),
    sa.Column('perms_method', sa.String(length=8), nullable=True, comment='站内接口方法, get|post|put|delete|patch'),
    sa.Column('perms_path', sa.String(length=64), nullable=False, comment='站内接口路径'),
    sa.Column('perms_url', sa.String(length=255), nullable=True, comment='站外外链请求地址'),
    sa.Column('order', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_perms_current_id'), 'app_perms', ['current_id'], unique=False)
    op.create_index(op.f('ix_app_perms_id'), 'app_perms', ['id'], unique=False)
    op.create_index(op.f('ix_app_perms_order'), 'app_perms', ['order'], unique=False)
    op.create_index(op.f('ix_app_perms_parent_id'), 'app_perms', ['parent_id'], unique=False)
    op.create_table('app_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=16), nullable=False, comment='角色名'),
    sa.Column('role_code', sa.String(length=16), nullable=False, comment='角色标识，不能修改'),
    sa.Column('remark', sa.String(length=256), nullable=True, comment='备注'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_role_id'), 'app_role', ['id'], unique=False)
    op.create_index(op.f('ix_app_role_role_code'), 'app_role', ['role_code'], unique=True)
    op.create_index(op.f('ix_app_role_role_name'), 'app_role', ['role_name'], unique=True)
    op.create_table('app_role_perms_rel',
    sa.Column('role_id', sa.Integer(), nullable=True, comment='角色唯一标识'),
    sa.Column('perms_id', sa.Integer(), nullable=True, comment='权限唯一标识')
    )
    op.create_index(op.f('ix_app_role_perms_rel_perms_id'), 'app_role_perms_rel', ['perms_id'], unique=False)
    op.create_index(op.f('ix_app_role_perms_rel_role_id'), 'app_role_perms_rel', ['role_id'], unique=False)
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False, comment='自增ID，在单库单表中唯一'),
    sa.Column('user_uuid', sa.String(length=50), nullable=True, comment='uuid'),
    sa.Column('user_code', sa.String(length=6), nullable=True, comment='邀请码'),
    sa.Column('user_name', sa.String(length=50), nullable=True, comment='用户名'),
    sa.Column('display_name', sa.String(length=50), nullable=True, comment='界面显示名（昵称）'),
    sa.Column('password_digest', sa.String(length=256), nullable=False, comment='登录用户密码的哈希值'),
    sa.Column('status', sa.Integer(), nullable=True, comment='帐号状态'),
    sa.Column('avatar', sa.String(length=256), nullable=True, comment='头像'),
    sa.Column('gender', sa.Integer(), nullable=True, comment='性别'),
    sa.Column('birthday', sa.Date(), nullable=True, comment='生日'),
    sa.Column('language', sa.String(length=8), nullable=True, comment='语言, zh-CN|en-US|en-GB'),
    sa.Column('bio', sa.String(length=500), nullable=True, comment='个人简介'),
    sa.Column('email', sa.String(length=256), nullable=True, comment='邮箱地址'),
    sa.Column('phone', sa.String(length=16), nullable=True, comment='手机号'),
    sa.Column('country', sa.String(length=50), nullable=True, comment='国家'),
    sa.Column('city', sa.String(length=50), nullable=True, comment='城市'),
    sa.Column('address', sa.String(length=256), nullable=True, comment='地址'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('last_login', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=True, server_default=sa.text("false"), comment='用户是否被删除'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=False)
    op.create_index(op.f('ix_app_user_id'), 'app_user', ['id'], unique=False)
    op.create_index(op.f('ix_app_user_phone'), 'app_user', ['phone'], unique=False)
    op.create_index(op.f('ix_app_user_user_code'), 'app_user', ['user_code'], unique=True)
    op.create_index(op.f('ix_app_user_user_name'), 'app_user', ['user_name'], unique=True)
    op.create_index(op.f('ix_app_user_user_uuid'), 'app_user', ['user_uuid'], unique=True)
    op.create_table('app_user_role_rel',
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户唯一标识'),
    sa.Column('role_id', sa.Integer(), nullable=True, comment='角色唯一标识')
    )
    op.create_index(op.f('ix_app_user_role_rel_role_id'), 'app_user_role_rel', ['role_id'], unique=False)
    op.create_index(op.f('ix_app_user_role_rel_user_id'), 'app_user_role_rel', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_user_role_rel_user_id'), table_name='app_user_role_rel')
    op.drop_index(op.f('ix_app_user_role_rel_role_id'), table_name='app_user_role_rel')
    op.drop_table('app_user_role_rel')
    op.drop_index(op.f('ix_app_user_user_uuid'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_user_name'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_user_code'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_phone'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_id'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    op.drop_index(op.f('ix_app_role_perms_rel_role_id'), table_name='app_role_perms_rel')
    op.drop_index(op.f('ix_app_role_perms_rel_perms_id'), table_name='app_role_perms_rel')
    op.drop_table('app_role_perms_rel')
    op.drop_index(op.f('ix_app_role_role_name'), table_name='app_role')
    op.drop_index(op.f('ix_app_role_role_code'), table_name='app_role')
    op.drop_index(op.f('ix_app_role_id'), table_name='app_role')
    op.drop_table('app_role')
    op.drop_index(op.f('ix_app_perms_parent_id'), table_name='app_perms')
    op.drop_index(op.f('ix_app_perms_order'), table_name='app_perms')
    op.drop_index(op.f('ix_app_perms_id'), table_name='app_perms')
    op.drop_index(op.f('ix_app_perms_current_id'), table_name='app_perms')
    op.drop_table('app_perms')
    op.drop_index(op.f('ix_app_auth_sns_user_uuid'), table_name='app_auth_sns')
    op.drop_index(op.f('ix_app_auth_sns_provider'), table_name='app_auth_sns')
    op.drop_index(op.f('ix_app_auth_sns_openid'), table_name='app_auth_sns')
    op.drop_index(op.f('ix_app_auth_sns_email'), table_name='app_auth_sns')
    op.drop_index('idx_user_provider', table_name='app_auth_sns')
    op.drop_table('app_auth_sns')
    op.drop_index(op.f('ix_app_auth_logs_user_uuid'), table_name='app_auth_logs')
    op.drop_table('app_auth_logs')
    op.drop_index(op.f('ix_app_auth_device_user_uuid'), table_name='app_auth_device')
    op.drop_index(op.f('ix_app_auth_device_push_token'), table_name='app_auth_device')
    op.drop_index('idx_u_d_p', table_name='app_auth_device')
    op.drop_table('app_auth_device')
    # ### end Alembic commands ###
